### ISSUE TITLE
Get combined badge and stats for same gh + npm package

### ISSUE THREAD

**Issue by metaist** [jsdelivr/data.jsdelivr.com#10]
If I publish code on github and npm, I'd like the jsDelivr badge to report combined stats for both. (Yay vanity metrics!)

To avoid abuse (e.g., a badge that combines stats for an unknown project with the stats for an unrelated popular project), perhaps you could use the repository field in `package.json` to make the correlation. It appears that field is already extracted somewhere because it appears on the page for packages.

**Comment by MartinKolarik** [comment]
We did consider doing this when designing the first API version (same problem applies to all stats endpoints, not just badges) and indeed, my idea was using the repository field from `package.json` to link the appropriate GitHub repo.

In the end we didn't do this because:
 - it would make the API more complex and more confusing for users
 - we don't have the package.json info available on the API side (our website takes it from a different source)

The third, and probably most important reason: We recommend that people always use npm links when possible, and as a package author you have the opportunity to put those links in the official documentation. If you do that, most of your users will just use the recommended links and the GitHub hits become so insignificant that combining them isn't necessary.

**Comment by metaist** [comment]
Thank you for getting back to me. These are all fair points. Obviously, not having the `package.json` on the API side makes this much more complicated than I imagined.

Just to be clear: I was inspired in part by the ability to request multiple packages with a single request (so that idiom kinda already exists) and by #9 to think of jsDelivr as delivering a package that happens to be hosted on npm or github or somewhere else in the future-- the stats simply reflect how many times that particular code has been delivered.

Feel free to close the issue if there's nothing else to consider; I'm totally fine just switching over to the npm links and ignoring the other traffic.

Thanks again and thank you to the whole team for making something that's absurdly useful.

**Comment by MartinKolarik** [comment]
>I was inspired in part by the ability to request multiple packages with a single request (so that idiom kinda already exists)

Indeed, after your first post I considered a similar `/combine` approach for the API, which would remove the problem of matching npm packages to the corresponding GitHub repos. 

I'll close this for now and we may revisit the idea if it becomes more important in the feature.
