### ISSUE TITLE
Download stats for custom CDN endpoints

### ISSUE THREAD

**Issue by rth** [jsdelivr/data.jsdelivr.com#49]
I was wondering if there is any way to get the download stats for custom CND endpoints (and in particular `cdn.jsdelivr.net/pyodide/`).

We talked about it a year or so ago, and it was costly to obtain at the time. So just opening this issue in case the situation changed since (I seem to remember some Github discussions about this but I could be wrong).

If there is anything we can contribute to make this easier, please let me know.

**Comment by jimaek** [comment]
Yep we're working on it https://www-jsdelivr-com-pr-400.onrender.com/custom-cdn-oss/pyodide

@MartinKolarik will have a bit more information about the current API state

**Comment by MartinKolarik** [comment]
It is already available in the preview version and soon will be integrated into the main one: https://data-jsdelivr-com-preview.onrender.com/v1/stats/proxies/pyodide?period=month

For selected projects, we'll also visualize it on the website as @jimaek mentioned.

**Comment by rth** [comment]
Great, thanks a lot for working on this! Bandwidth is uncompressed size, right? 

Finer file granularity would have been nice, but I imagine it's harder and this is already extremely helpful. Thank you!

**Comment by MartinKolarik** [comment]
Bandwidth is the real transmitted size so usually compressed.

File stats - maybe we could but it opens questions about versioning. Would it be useful if we considered the whole path after the prefix the filename, or would it need to have similar structure to npm packages: project -> version -> file? And iirc you have something like `latest` too?

**Comment by rth** [comment]
Thanks for the explications!

Well yes, in the case of Pyodide the full path would be nice if it's not too difficult. In terms of URL currently, we have a distribution model (so there is a fixed set of packages for a given release) so the URL is something like,
```
/pyodide/<distribution version>/<build type currently just "full">/<package name + version>
```
(where the "version" could also be "dev" i.e. latest)
but in the near future, we are considering switching to a more common model where a given package can have multiple versions. So we are considering making it something like,
```
/pyodide / < prefix TDB> / <package-name> / <file>
```
Though then it's unclear what to do with dev deployment, maybe we should host it separately.

Just FYI, in case it's useful information for designing your stats API (or if you have some  URL schema recommendations we should follow when possible).

**Comment by MartinKolarik** [comment]
The problem here is both the storage and the API response schemas would have to be generic enough to fit all custom endpoints and still somewhat make sense.

E.g., if we went with a simple "version"/"file" breakdown, I suppose in your current setup, the "distribution version" could be mapped to "version", and the rest to "file". But maybe that's not even useful because you actually have "packages" which have their own version and to give you fully organized data, it would have to be broken down to release -> package -> version or maybe just package -> version, which isn't at all generic.

I'm thinking that if we were to add more details, it would be best to have just a list of top files, with no extra grouping, and you could then run whatever aggregations on it yourself.

**Comment by MartinKolarik** [comment]
Hey @rth, I just wanted to check if you have any input on my last comment.

**Comment by rth** [comment]
Yes, sorry for the lack of response.

I agree it's a bit complicated problem, in our case particularly given that we are not really sure how the file path structure is going to look in the future.

>  it would be best to have just a list of top files, with no extra grouping

That would certainly work for us, and I agree it's probably the most general solution.

In any case thanks a lot for working on this @MartinKolarik !

**Comment by MartinKolarik** [comment]
I added an experimental endpoint for this: https://data-jsdelivr-com-preview.onrender.com/v1/stats/proxies/pyodide/files

![image](https://user-images.githubusercontent.com/6192491/197388190-7a5ded5f-09b6-4a61-b723-966d208c68b2.png)

Note that we've been collecting this data since October 3 so even though the default is 1 month, the values are not complete yet.

**Comment by rth** [comment]
This is great, thank you @MartinKolarik !

**Comment by MartinKolarik** [comment]
This is now available at https://data.jsdelivr.com/v1/stats/proxies/pyodide/files. The preview domain will be shutdown soon.
