### ISSUE TITLE
Looking up packages by query

### ISSUE THREAD

**Issue by oskarkrawczyk** [jsdelivr/data.jsdelivr.com#8]
Hi this is Oskar from JSFiddle.

I've been looking into using the API for our NPM needs, one thing that would be needed is a way to search for packages by the name string.

Is this by any chance on your roadmap for the API?

**Comment by MartinKolarik** [comment]
Hi Oskar, please see https://github.com/jsdelivr/data.jsdelivr.com/issues/7#issuecomment-358286324 and #6. I'd recommend using Algolia search in this case. As I mentioned on Twitter, I'll be happy to help you with this if needed.

In theory, we could add an endpoint for searching, which would proxy requests to Algolia - it would probably be slightly easier to use, but would have significantly higher latency and therefore worse UX. Let me know what you think.

**Comment by MartinKolarik** [comment]
TIL searching by package name is also possible directly via the public npmjs registry API: https://registry.npmjs.org/-/v1/search?text=jquery

Documentation: https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md#get-v1search

We should probably mention this in our readme so that people find this easier in the future, and consider this problem solved.

**Comment by MartinKolarik** [comment]
Added to the readme. @oskarkrawczyk let me know if you have any other questions.
